# Generated by Django 3.0 on 2020-06-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_number_of_players', models.IntegerField()),
                ('registered_teams', models.ManyToManyField(to='tournaments_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('is_win', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments_app.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number_of_players', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.Round')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_a_team', to='tournaments_app.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_b_team', to='tournaments_app.Team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_win_team', to='tournaments_app.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.Group'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_a_team', to='tournaments_app.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_b_team', to='tournaments_app.Team'),
        ),
    ]
