# Generated by Django 2.2.8 on 2020-06-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('is_win', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments_app.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments_app.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='score_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_core_a_team', to='tournaments_app.Score'),
        ),
        migrations.AddField(
            model_name='game',
            name='score_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_score_b_team', to='tournaments_app.Score'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_a_team', to='tournaments_app.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_b_team', to='tournaments_app.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.Tournament'),
        ),
    ]
