# Generated by Django 3.0 on 2020-06-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
    ]
