# Generated by Django 3.0.7 on 2020-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0002_auto_20200606_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registered_teams',
            field=models.ManyToManyField(to='tournaments_app.Team'),
        ),
    ]
