# Generated by Django 3.0.7 on 2020-06-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0003_tournament_registered_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='registered_tournaments',
            field=models.ManyToManyField(to='tournaments_app.Tournament'),
        ),
    ]
