# Generated by Django 3.0.7 on 2020-06-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0004_team_registered_tournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='registered_tournaments',
            field=models.ManyToManyField(blank=True, null=True, to='tournaments_app.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registered_teams',
            field=models.ManyToManyField(blank=True, null=True, to='tournaments_app.Team'),
        ),
    ]
