# Generated by Django 2.2.8 on 2020-06-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0005_auto_20200607_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='registered_tournaments',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registered_teams',
            field=models.ManyToManyField(to='tournaments_app.Team'),
        ),
    ]
