# Generated by Django 2.2.8 on 2020-06-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0006_auto_20200607_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='tournaments_app.Player', verbose_name=models.AutoField(db_index=True, primary_key=True, serialize=False)),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments_app.Team'),
        ),
    ]
