# Generated by Django 2.2.8 on 2020-06-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0007_auto_20200607_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
    ]
