# Generated by Django 3.0.7 on 2020-06-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0009_auto_20200608_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registerd_games',
            field=models.ManyToManyField(related_name='tournament_registerd_games', to='tournaments_app.Game'),
        ),
    ]
