# Generated by Django 2.2.8 on 2020-06-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0010_tournament_registerd_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='registerd_games',
        ),
    ]
