# Generated by Django 2.2.8 on 2020-06-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0011_remove_tournament_registerd_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('number_of_players', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.Round')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_a_team', to='tournaments_app.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_b_team', to='tournaments_app.Team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_win_team', to='tournaments_app.Team')),
            ],
        ),
    ]
