# Generated by Django 2.2.8 on 2020-06-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0012_group_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.Group'),
            preserve_default=False,
        ),
    ]
