# Generated by Django 2.2.8 on 2020-06-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0013_auto_20200609_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_win_team', to='tournaments_app.Team'),
        ),
    ]
