# Generated by Django 2.2.8 on 2020-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0014_auto_20200609_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
