# Generated by Django 2.2.8 on 2020-06-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.Team')),
            ],
        ),
    ]
